name: AmberValley
authority_code: ambervalley
platform: ambervalley
base_url: https://www.ambervalley.gov.uk/planning/development-management/view-a-planning-application/
schedule: 0 3 * * *
requires_js: false
enabled: true
