name: Anglesey
authority_code: anglesey
platform: None
base_url: "http://www.anglesey.gov.uk/planning-and-waste/planning-control/view-list-of-current-and-previous-planning-applications"
schedule: "0 3 * * *"
requires_js: false
enabled: false
# No scraper - site has PDFs only
