name: BreconBeacons
authority_code: breconbeacons
platform: bespoke
base_url: https://beacons-npa.gov.uk/planning/applications/applications-online/apps-online/
schedule: 0 3 * * *
requires_js: false
enabled: false
