name: Dartmoor
authority_code: dartmoor
platform: unsupported
base_url: "http://www.dartmoor.gov.uk/planning"
schedule: "0 3 * * *"
requires_js: false
enabled: false
# was custom ListScraper up to Aug 2016
