name: Middlesbrough
authority_code: middlesbrough
platform: agile
base_url: https://planning.agileapplications.co.uk/middlesbrough/search-applications/
schedule: 0 3 * * *
requires_js: false
enabled: false
