name: RibbleValley
authority_code: ribblevalley
platform: bespoke
base_url: https://webportal.ribblevalley.gov.uk/planningApplication/search/advanced
schedule: 0 3 * * *
requires_js: false
enabled: false
