name: SouthLanarkshire
authority_code: southlanarkshire
platform: planning_explorer
base_url: "http://pbsportal.southlanarkshire.gov.uk/Northgate/PlanningExplorer"
schedule: "0 3 * * *"
requires_js: false
enabled: false
