name: StaffordshireMoorlands
authority_code: staffordshiremoorlands
platform: appsearchserv
base_url: http://publicaccess.staffsmoorlands.gov.uk/portal/servlets/ApplicationSearchServlet
schedule: 0 3 * * *
requires_js: false
enabled: true
