name: Warrington
authority_code: warrington
platform: swiftlg
base_url: https://planning.warrington.gov.uk/swiftlg/apas/run/wphappcriteria.display
schedule: 0 3 * * *
requires_js: false
enabled: true
