name: WestLancashire
authority_code: westlancashire
platform: idox
base_url: "http://publicaccess.westlancsdc.gov.uk/PublicAccess/tdc/DcApplication"
schedule: "0 3 * * *"
requires_js: false
enabled: false
