name: Worcestershire
authority_code: worcestershire
platform: swiftlg
base_url: https://e-planning.worcestershire.gov.uk/swift/apas/run/wchvarylogin.display
schedule: 0 3 * * *
requires_js: false
enabled: true
