name: WyreForest
authority_code: wyreforest
platform: bespoke
base_url: https://www.wyreforestdc.gov.uk/planning-and-buildings/search-for-a-planning-application/
schedule: 0 3 * * *
requires_js: false
enabled: false
