name: YorkshireDales
authority_code: yorkshiredales
platform: agile
base_url: https://planning.agileapplications.co.uk/yorkshiredales/search-applications/
schedule: 0 3 * * *
requires_js: false
enabled: false
